repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
  - repo: https://github.com/PyCQA/bandit
    rev: 5a1c4f0
    hooks:
      - id: bandit
#  - repo: local
#    hooks:
#      - id: tests
#        name: run tests
#        entry: pytest -v
#        language: system
#        types: [python]
#        stages: [push]