repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    sha: v1.0.3
    hooks:
      - id: python-bandit-vulnerability-check
        args: [-l, --recursive, -x, tests]
        files: .py$
#  - repo: local
#    hooks:
#      - id: tests
#        name: run tests
#        entry: pytest -v
#        language: system
#        types: [python]
#        stages: [push]